- name: Add Packer GPG Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Packer Repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com jammy main
    state: present

- name: Update apt and install Packer
  apt:
    name: packer
    state: latest
    update_cache: true

- name: Set Packer logging
  ansible.builtin.shell: |
    export PACKER_LOG=1
    export PACKER_LOG_PATH="packer_build.log"

- name: Run Packer Init
  ansible.builtin.shell: |
    packer init .
  args:
    chdir: ./build/{{ template_selection }}/

- name: Run Packer Build
  ansible.builtin.shell: |
    packer build --force .
  args:
    chdir: ./build/{{ template_selection }}/