variables:
- group: packer_esxi_variables_host_01
- group: packer_esxi_variables_windows

parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: templateSelection
  displayName: Packer Template Selection
  default: windows
  values:
    - windows
    - linux

trigger:
- none

stages:

- stage: 'packerinstall'
  dependsOn: []
  displayName: 'Packer Install'

  jobs:
    - job: 'packerinstall'
      displayName: 'Packer Install'
      pool: ${{ parameters.agentPool }}

      steps:

      - task: Ansible@0
        displayName: Packer Install
        inputs:
          ansibleInterface: 'agentMachine'
          inventoriesAgentMachine: 'noInventory'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/packer_install.yml'
          failOnStdErr: false

- stage: 'packerbuild'
  dependsOn: [packerinstall]
  displayName: 'Packer Build'

  jobs:
    - job: 'packerbuild'
      displayName: 'Packer Build'
      pool: ${{ parameters.agentPool }}
      timeoutInMinutes: 180

      steps:

      - checkout: none

      - task: replacetokens@5
        displayName: Replace Tokens
        inputs:
          rootDirectory: '$(System.DefaultWorkingDirectory)/build/${{ parameters.templateSelection }}/'
          targetFiles: '**/*.*'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          enableTelemetry: false

      - task: replacetokens@5
        condition: eq('${{ parameters.templateSelection }}', 'windows' )
        displayName: Replace Tokens for XML
        inputs:
          rootDirectory: '$(System.DefaultWorkingDirectory)/build/scripts/${{ parameters.templateSelection }}/'
          targetFiles: '**/*.*'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          enableTelemetry: false

      - task: CmdLine@2
        displayName: Run Packer Build
        inputs:
          script: |
            packer init .
            packer build --force .
          workingDirectory: '$(System.DefaultWorkingDirectory)/build/${{ parameters.templateSelection }}/'

      - task: PublishBuildArtifacts@1
        displayName: Publish Packer Build Log
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/packer_build.log'
          ArtifactName: 'packer_build_log_$(Build.BuildNumber)_$(Year:yyyy).$(Month).$(DayOfMonth)'
          publishLocation: 'Container'