variables:
- group: packer_esxi_variables_host_01
- group: packer_esxi_variables_windows
- group: packer_esxi_variables_linux

parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: templateSelection
  displayName: Packer Template Selection
  default: windows
  values:
    - windows
    - linux

trigger:
- none

stages:

- stage: 'packerbuild'
  dependsOn: []
  displayName: 'Packer Build'

  jobs:
    - job: 'packerbuild'
      displayName: 'Packer Build'
      pool: ${{ parameters.agentPool }}
      timeoutInMinutes: 180

      steps:

      - task: replacetokens@5
        inputs:
          rootDirectory: '$(System.DefaultWorkingDirectory)/build/{{ parameters.templateSelection }}/'
          targetFiles: '**/*.*'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          enableTelemetry: false

      - task: Ansible@0
        displayName: Packer Binary Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/packer_build.yml'
          inventoriesAgentMachine: 'file'
          args: '--extra-vars "nodes=${{ parameters.nodeSelection }} template_selection=${{ parameters.templateSelection }}"'
          failOnStdErr: false