variables:
- group: packer_esxi_variables_host_02
- group: packer_esxi_variables_linux

parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud

trigger:
- none

stages:

- stage: 'packerinstall'
  dependsOn: []
  displayName: 'Packer Install'

  jobs:
    - job: 'packerinstall'
      displayName: 'Packer Install'
      pool: ${{ parameters.agentPool }}

      steps:

      - task: Ansible@0
        displayName: Packer Install
        inputs:
          ansibleInterface: 'agentMachine'
          inventoriesAgentMachine: 'noInventory'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/packer_install.yml'
          failOnStdErr: false

- stage: 'packerbuild'
  dependsOn: [packerinstall]
  displayName: 'Packer Build'

  jobs:
    - job: 'packerbuild'
      displayName: 'Packer Build'
      pool: ${{ parameters.agentPool }}
      timeoutInMinutes: 180

      steps:

      - checkout: none

      - task: replacetokens@5
        displayName: Replace Tokens for Cloud Init
        inputs:
          rootDirectory: '$(System.DefaultWorkingDirectory)/build/linux/http/'
          targetFiles: 'user-data'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          enableTelemetry: false

      - task: replacetokens@5
        displayName: Replace Tokens
        inputs:
          rootDirectory: '$(System.DefaultWorkingDirectory)/build/linux/'
          targetFiles: '**/*.*'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          enableTelemetry: false

      - task: SSH@0
        displayName: Remove existing Packer artifact
        inputs:
          sshEndpoint: 'ESXI Host 02'
          runOptions: inline
          inline: |
            VM_NAME="$(vm_name)"; 
            VM_ID=$(vim-cmd vmsvc/getallvms | grep "$VM_NAME" | awk '{print $1}'); 
            if [ -n "$VM_ID" ]; 
            then echo "Found VM ID: $VM_ID"; 
            vim-cmd vmsvc/destroy "$VM_ID"; 
            echo "VM removed successfully."; 
            else echo "VM not found or already removed."; 
            fi

      - task: CmdLine@2
        displayName: Run Packer Build
        inputs:
          script: |
            packer init .
            packer build --force .
          workingDirectory: '$(System.DefaultWorkingDirectory)/build/linux/'