- name: Remove Packer artifact
  community.vmware.vmware_guest:
    hostname: "#{REMOTE_HOST}#"
    username: "#{REMOTE_USERNAME}#"
    password: "#{REMOTE_PASSWORD}#"
    validate_certs: false
    name: "{{ VM_NAME }}"
    state: absent
  delegate_to: localhost